import { defineField, defineType } from "sanity";
import { seoFields } from "./objects";

export const destination = defineType({
  name: "destination",
  title: "Destination",
  type: "document",
  groups: [
    { name: "content", title: "Content", default: true },
    { name: "seo", title: "SEO" },
  ],
  fields: [
    defineField({
      name: "title",
      title: "Title",
      type: "string",
      group: "content",
      validation: (rule) => rule.required(),
    }),
    defineField({
      name: "slug",
      title: "Slug",
      type: "slug",
      group: "content",
      options: { source: "title", maxLength: 96 },
      validation: (rule) => rule.required(),
    }),
    defineField({
      name: "region",
      title: "Region label",
      type: "string",
      group: "content",
      initialValue: "Kashmir",
    }),
    defineField({
      name: "headline",
      title: "Page headline (H1)",
      type: "string",
      group: "content",
    }),
    defineField({
      name: "description",
      title: "Description",
      type: "text",
      rows: 4,
      group: "content",
      validation: (rule) => rule.required(),
    }),
    defineField({
      name: "introduction",
      title: "Introduction",
      type: "text",
      rows: 6,
      group: "content",
      validation: (rule) => rule.required(),
    }),
    defineField({
      name: "whyVisit",
      title: "Why visit",
      type: "array",
      group: "content",
      of: [{ type: "labeledItem" }],
    }),
    defineField({
      name: "attractions",
      title: "Attractions",
      type: "array",
      group: "content",
      of: [{ type: "labeledItem" }],
      validation: (rule) => rule.min(1),
    }),
    defineField({
      name: "thingsToDo",
      title: "Things to do",
      type: "array",
      group: "content",
      of: [{ type: "labeledItem" }],
      validation: (rule) => rule.min(1),
    }),
    defineField({
      name: "suggestedDuration",
      title: "Suggested stay",
      type: "object",
      group: "content",
      fields: [
        defineField({ name: "typicalStay", title: "Typical stay", type: "string" }),
        defineField({ name: "overview", title: "Overview", type: "text", rows: 3 }),
      ],
    }),
    defineField({
      name: "bestTime",
      title: "Best time",
      type: "object",
      group: "content",
      fields: [
        defineField({ name: "overview", title: "Overview", type: "text", rows: 3 }),
        defineField({
          name: "seasons",
          title: "Seasons",
          type: "array",
          of: [{ type: "seasonItem" }],
        }),
      ],
    }),
    defineField({
      name: "travelInformation",
      title: "Travel information",
      type: "object",
      group: "content",
      fields: [
        defineField({ name: "overview", title: "Overview", type: "text", rows: 3 }),
        defineField({
          name: "details",
          title: "Details",
          type: "array",
          of: [{ type: "string" }],
        }),
      ],
    }),
    defineField({
      name: "nearbyDestinations",
      title: "Nearby destinations",
      type: "array",
      group: "content",
      of: [{ type: "reference", to: [{ type: "destination" }] }],
    }),
    defineField({
      name: "heroImage",
      title: "Hero image",
      type: "altImage",
      group: "content",
      validation: (rule) => rule.required(),
    }),
    defineField({
      name: "images",
      title: "Images",
      type: "array",
      group: "content",
      of: [{ type: "altImage" }],
    }),
    defineField({
      name: "faqs",
      title: "FAQs",
      type: "array",
      group: "content",
      of: [{ type: "faqItem" }],
    }),
    defineField({
      name: "featured",
      title: "Featured",
      type: "boolean",
      group: "content",
      initialValue: false,
    }),
    defineField({
      name: "published",
      title: "Published",
      type: "boolean",
      group: "content",
      initialValue: false,
    }),
    ...seoFields,
  ],
  preview: {
    select: { title: "title", media: "heroImage", published: "published" },
    prepare: ({ title, media, published }) => ({
      title,
      subtitle: published ? "Published" : "Draft",
      media,
    }),
  },
});
