import { defineField, defineType } from "sanity";
import { seoFields } from "./objects";

export const travelPackage = defineType({
  name: "travelPackage",
  title: "Travel package",
  type: "document",
  groups: [
    { name: "content", title: "Content", default: true },
    { name: "pricing", title: "Price" },
    { name: "seo", title: "SEO" },
  ],
  fields: [
    defineField({
      name: "title",
      title: "Title",
      type: "string",
      group: "content",
      validation: (rule) => rule.required(),
    }),
    defineField({
      name: "slug",
      title: "Slug",
      type: "slug",
      group: "content",
      options: { source: "title", maxLength: 96 },
      validation: (rule) => rule.required(),
    }),
    defineField({
      name: "shortDescription",
      title: "Short description",
      type: "text",
      rows: 3,
      group: "content",
      validation: (rule) => rule.required(),
    }),
    defineField({
      name: "description",
      title: "Description",
      type: "text",
      rows: 6,
      group: "content",
      validation: (rule) => rule.required(),
    }),
    defineField({
      name: "duration",
      title: "Duration",
      type: "string",
      group: "content",
      description: 'Example: "5 nights / 6 days"',
      validation: (rule) => rule.required(),
    }),
    defineField({
      name: "primaryDestination",
      title: "Primary destination",
      type: "reference",
      group: "content",
      to: [{ type: "destination" }],
      validation: (rule) => rule.required(),
    }),
    defineField({
      name: "destinations",
      title: "Destinations",
      type: "array",
      group: "content",
      of: [{ type: "reference", to: [{ type: "destination" }] }],
      validation: (rule) => rule.min(1),
    }),
    defineField({
      name: "packageType",
      title: "Package type",
      type: "string",
      group: "content",
      options: {
        list: [
          { title: "Honeymoon", value: "honeymoon" },
          { title: "Family", value: "family" },
          { title: "Group", value: "group" },
          { title: "Kashmir circuit", value: "sightseeing" },
          { title: "Custom", value: "custom" },
        ],
        layout: "radio",
      },
      validation: (rule) => rule.required(),
    }),
    defineField({
      name: "startingPrice",
      title: "Price",
      type: "number",
      group: "pricing",
      description:
        "Leave empty until a real tariff is confirmed. Never invent a figure.",
    }),
    defineField({
      name: "priceNote",
      title: "Price note",
      type: "text",
      rows: 2,
      group: "pricing",
      description:
        "Shown under the price. Leave empty to use “Contact us for current pricing”. Do not put a fake rupee figure here.",
    }),
    defineField({
      name: "priceCurrency",
      title: "Currency",
      type: "string",
      group: "pricing",
      initialValue: "INR",
      readOnly: true,
    }),
    defineField({
      name: "heroImage",
      title: "Hero image",
      type: "altImage",
      group: "content",
      validation: (rule) => rule.required(),
    }),
    defineField({
      name: "gallery",
      title: "Gallery",
      type: "array",
      group: "content",
      of: [{ type: "altImage" }],
    }),
    defineField({
      name: "itinerary",
      title: "Itinerary",
      type: "array",
      group: "content",
      of: [{ type: "itineraryDay" }],
      validation: (rule) => rule.min(1),
    }),
    defineField({
      name: "inclusions",
      title: "Inclusions",
      type: "array",
      group: "content",
      of: [{ type: "string" }],
    }),
    defineField({
      name: "exclusions",
      title: "Exclusions",
      type: "array",
      group: "content",
      of: [{ type: "string" }],
    }),
    defineField({
      name: "hotels",
      title: "Stays",
      type: "array",
      group: "content",
      of: [{ type: "hotelStay" }],
      description: "Hotel names stay empty until confirmed in a quote.",
    }),
    defineField({
      name: "transportation",
      title: "Transportation",
      type: "object",
      group: "content",
      fields: [
        defineField({ name: "overview", title: "Overview", type: "text", rows: 3 }),
        defineField({
          name: "details",
          title: "Details",
          type: "array",
          of: [{ type: "string" }],
        }),
      ],
    }),
    defineField({
      name: "meals",
      title: "Meals",
      type: "object",
      group: "content",
      fields: [
        defineField({ name: "overview", title: "Overview", type: "text", rows: 3 }),
        defineField({ name: "plan", title: "Meal plan", type: "string" }),
      ],
    }),
    defineField({
      name: "importantNotes",
      title: "Important notes",
      type: "array",
      group: "content",
      of: [{ type: "string" }],
    }),
    defineField({
      name: "faqs",
      title: "FAQs",
      type: "array",
      group: "content",
      of: [{ type: "faqItem" }],
    }),
    defineField({
      name: "featured",
      title: "Featured",
      type: "boolean",
      group: "content",
      initialValue: false,
    }),
    defineField({
      name: "published",
      title: "Published",
      type: "boolean",
      group: "content",
      initialValue: false,
      description: "Unpublished packages never appear on the website.",
    }),
    ...seoFields,
  ],
  preview: {
    select: {
      title: "title",
      media: "heroImage",
      published: "published",
    },
    prepare: ({ title, media, published }) => ({
      title,
      subtitle: published ? "Published" : "Draft",
      media,
    }),
  },
});
